import * as _dbbcsd from "./functions/dbbcsd";
import * as _dbdsqr from "./functions/dbdsqr";
import * as _ddisna from "./functions/ddisna";
import * as _dgbbrd from "./functions/dgbbrd";
import * as _dgbcon from "./functions/dgbcon";
import * as _dgbequ from "./functions/dgbequ";
import * as _dgbequb from "./functions/dgbequb";
import * as _dgbrfs from "./functions/dgbrfs";
import * as _dgbsv from "./functions/dgbsv";
import * as _dgbsvx from "./functions/dgbsvx";
import * as _dgbtf2 from "./functions/dgbtf2";
import * as _dgbtrf from "./functions/dgbtrf";
import * as _dgbtrs from "./functions/dgbtrs";
import * as _dgebak from "./functions/dgebak";
import * as _dgebal from "./functions/dgebal";
import * as _dgebd2 from "./functions/dgebd2";
import * as _dgebrd from "./functions/dgebrd";
import * as _dgecon from "./functions/dgecon";
import * as _dgeequ from "./functions/dgeequ";
import * as _dgeequb from "./functions/dgeequb";
import * as _dgeev from "./functions/dgeev";
import * as _dgeevx from "./functions/dgeevx";
import * as _dgehd2 from "./functions/dgehd2";
import * as _dgehrd from "./functions/dgehrd";
import * as _dgejsv from "./functions/dgejsv";
import * as _dgelq from "./functions/dgelq";
import * as _dgelq2 from "./functions/dgelq2";
import * as _dgelqf from "./functions/dgelqf";
import * as _dgelqt from "./functions/dgelqt";
import * as _dgels from "./functions/dgels";
import * as _dgelss from "./functions/dgelss";
import * as _dgelsy from "./functions/dgelsy";
import * as _dgemqr from "./functions/dgemqr";
import * as _dgeql2 from "./functions/dgeql2";
import * as _dgeqlf from "./functions/dgeqlf";
import * as _dgeqp3 from "./functions/dgeqp3";
import * as _dgeqr from "./functions/dgeqr";
import * as _dgeqr2 from "./functions/dgeqr2";
import * as _dgeqr2p from "./functions/dgeqr2p";
import * as _dgeqrf from "./functions/dgeqrf";
import * as _dgeqrfp from "./functions/dgeqrfp";
import * as _dgeqrt from "./functions/dgeqrt";
import * as _dgeqrt2 from "./functions/dgeqrt2";
import * as _dgerfs from "./functions/dgerfs";
import * as _dgerq2 from "./functions/dgerq2";
import * as _dgerqf from "./functions/dgerqf";
import * as _dgesc2 from "./functions/dgesc2";
import * as _dgesv from "./functions/dgesv";
import * as _dgesvj from "./functions/dgesvj";
import * as _dgesvx from "./functions/dgesvx";
import * as _dgetc2 from "./functions/dgetc2";
import * as _dgetf2 from "./functions/dgetf2";
import * as _dgetrf from "./functions/dgetrf";
import * as _dgetri from "./functions/dgetri";
import * as _dgetrs from "./functions/dgetrs";
import * as _dgetsls from "./functions/dgetsls";
import * as _dggbak from "./functions/dggbak";
import * as _dggev from "./functions/dggev";
import * as _dggev3 from "./functions/dggev3";
import * as _dggglm from "./functions/dggglm";
import * as _dgghrd from "./functions/dgghrd";
import * as _dgglse from "./functions/dgglse";
import * as _dggqrf from "./functions/dggqrf";
import * as _dggrqf from "./functions/dggrqf";
import * as _dggsvd3 from "./functions/dggsvd3";
import * as _dggsvp3 from "./functions/dggsvp3";
import * as _dgsvj0 from "./functions/dgsvj0";
import * as _dgsvj1 from "./functions/dgsvj1";
import * as _dgtcon from "./functions/dgtcon";
import * as _dgtrfs from "./functions/dgtrfs";
import * as _dgtsv from "./functions/dgtsv";
import * as _dgtsvx from "./functions/dgtsvx";
import * as _dgttrf from "./functions/dgttrf";
import * as _dgttrs from "./functions/dgttrs";
import * as _dgtts2 from "./functions/dgtts2";
import * as _dhgeqz from "./functions/dhgeqz";
import * as _dhseqr from "./functions/dhseqr";
import * as _dlabad from "./functions/dlabad";
import * as _dlabrd from "./functions/dlabrd";
import * as _dlacn2 from "./functions/dlacn2";
import * as _dlacon from "./functions/dlacon";
import * as _dlacpy from "./functions/dlacpy";
import * as _dladiv from "./functions/dladiv";
import * as _dlae2 from "./functions/dlae2";
import * as _dlaebz from "./functions/dlaebz";
import * as _dlaed1 from "./functions/dlaed1";
import * as _dlaed2 from "./functions/dlaed2";
import * as _dlaed4 from "./functions/dlaed4";
import * as _dlaed5 from "./functions/dlaed5";
import * as _dlaed8 from "./functions/dlaed8";
import * as _dlaed9 from "./functions/dlaed9";
import * as _dlaev2 from "./functions/dlaev2";
import * as _dlag2 from "./functions/dlag2";
import * as _dlag2s from "./functions/dlag2s";
import * as _dlagtf from "./functions/dlagtf";
import * as _dlagtm from "./functions/dlagtm";
import * as _dlagts from "./functions/dlagts";
import * as _dlagv2 from "./functions/dlagv2";
import * as _dlahr2 from "./functions/dlahr2";
import * as _dlaic1 from "./functions/dlaic1";
import * as _dlamrg from "./functions/dlamrg";
import * as _dlanv2 from "./functions/dlanv2";
import * as _dlaqgb from "./functions/dlaqgb";
import * as _dlaqge from "./functions/dlaqge";
import * as _dlaqp2 from "./functions/dlaqp2";
import * as _dlaqr1 from "./functions/dlaqr1";
import * as _dlaqsb from "./functions/dlaqsb";
import * as _dlaqsp from "./functions/dlaqsp";
import * as _dlaqsy from "./functions/dlaqsy";
import * as _dlarnv from "./functions/dlarnv";
import * as _dlarra from "./functions/dlarra";
import * as _dlarrb from "./functions/dlarrb";
import * as _dlarrc from "./functions/dlarrc";
import * as _dlarrd from "./functions/dlarrd";
import * as _dlarre from "./functions/dlarre";
import * as _dlarrj from "./functions/dlarrj";
import * as _dlarrk from "./functions/dlarrk";
import * as _dlarrr from "./functions/dlarrr";
import * as _dlarrv from "./functions/dlarrv";
import * as _dlarscl2 from "./functions/dlarscl2";
import * as _dlartg from "./functions/dlartg";
import * as _dlartgp from "./functions/dlartgp";
import * as _dlartgs from "./functions/dlartgs";
import * as _dlaruv from "./functions/dlaruv";
import * as _dlas2 from "./functions/dlas2";
import * as _dlascl from "./functions/dlascl";
import * as _dlasd4 from "./functions/dlasd4";
import * as _dlasd5 from "./functions/dlasd5";
import * as _dlasdt from "./functions/dlasdt";
import * as _dlaset from "./functions/dlaset";
import * as _dlasq1 from "./functions/dlasq1";
import * as _dlasq2 from "./functions/dlasq2";
import * as _dlasq4 from "./functions/dlasq4";
import * as _dlasrt from "./functions/dlasrt";
import * as _dlassq from "./functions/dlassq";
import * as _dlasv2 from "./functions/dlasv2";
import * as _dlasyf from "./functions/dlasyf";
import * as _dlasyf_aa from "./functions/dlasyf_aa";
import * as _dlasyf_rk from "./functions/dlasyf_rk";
import * as _dlasyf_rook from "./functions/dlasyf_rook";
import * as _dlat2s from "./functions/dlat2s";
import * as _dlatbs from "./functions/dlatbs";
import * as _dlatdf from "./functions/dlatdf";
import * as _dlatps from "./functions/dlatps";
import * as _dlatrd from "./functions/dlatrd";
import * as _dlatrs from "./functions/dlatrs";
import * as _dlatrz from "./functions/dlatrz";
import * as _dlauu2 from "./functions/dlauu2";
import * as _dlauum from "./functions/dlauum";
import * as _dla_lin_berr from "./functions/dla_lin_berr";
import * as _dla_wwaddw from "./functions/dla_wwaddw";
import * as _dopgtr from "./functions/dopgtr";
import * as _dorbdb from "./functions/dorbdb";
import * as _dorbdb1 from "./functions/dorbdb1";
import * as _dorbdb2 from "./functions/dorbdb2";
import * as _dorbdb3 from "./functions/dorbdb3";
import * as _dorbdb4 from "./functions/dorbdb4";
import * as _dorbdb5 from "./functions/dorbdb5";
import * as _dorbdb6 from "./functions/dorbdb6";
import * as _dorg2l from "./functions/dorg2l";
import * as _dorg2r from "./functions/dorg2r";
import * as _dorghr from "./functions/dorghr";
import * as _dorgl2 from "./functions/dorgl2";
import * as _dorglq from "./functions/dorglq";
import * as _dorgql from "./functions/dorgql";
import * as _dorgqr from "./functions/dorgqr";
import * as _dorgr2 from "./functions/dorgr2";
import * as _dorgrq from "./functions/dorgrq";
import * as _dorgtr from "./functions/dorgtr";
import * as _dormql from "./functions/dormql";
import * as _dormqr from "./functions/dormqr";
import * as _dpbcon from "./functions/dpbcon";
import * as _dpbequ from "./functions/dpbequ";
import * as _dpbrfs from "./functions/dpbrfs";
import * as _dpbstf from "./functions/dpbstf";
import * as _dpbsv from "./functions/dpbsv";
import * as _dpbsvx from "./functions/dpbsvx";
import * as _dpbtf2 from "./functions/dpbtf2";
import * as _dpbtrf from "./functions/dpbtrf";
import * as _dpbtrs from "./functions/dpbtrs";
import * as _dpftrf from "./functions/dpftrf";
import * as _dpftri from "./functions/dpftri";
import * as _dpftrs from "./functions/dpftrs";
import * as _dpocon from "./functions/dpocon";
import * as _dpoequ from "./functions/dpoequ";
import * as _dpoequb from "./functions/dpoequb";
import * as _dporfs from "./functions/dporfs";
import * as _dposv from "./functions/dposv";
import * as _dposvx from "./functions/dposvx";
import * as _dpotf2 from "./functions/dpotf2";
import * as _dpotrf from "./functions/dpotrf";
import * as _dpotri from "./functions/dpotri";
import * as _dpotrs from "./functions/dpotrs";
import * as _dppcon from "./functions/dppcon";
import * as _dppequ from "./functions/dppequ";
import * as _dpprfs from "./functions/dpprfs";
import * as _dppsv from "./functions/dppsv";
import * as _dppsvx from "./functions/dppsvx";
import * as _dpptrf from "./functions/dpptrf";
import * as _dpptri from "./functions/dpptri";
import * as _dpptrs from "./functions/dpptrs";
import * as _dpstf2 from "./functions/dpstf2";
import * as _dpstrf from "./functions/dpstrf";
import * as _dptcon from "./functions/dptcon";
import * as _dpteqr from "./functions/dpteqr";
import * as _dptrfs from "./functions/dptrfs";
import * as _dptsv from "./functions/dptsv";
import * as _dptsvx from "./functions/dptsvx";
import * as _dpttrf from "./functions/dpttrf";
import * as _dpttrs from "./functions/dpttrs";
import * as _dptts2 from "./functions/dptts2";
import * as _dsbev from "./functions/dsbev";
import * as _dsbgst from "./functions/dsbgst";
import * as _dsbgv from "./functions/dsbgv";
import * as _dsbgvd from "./functions/dsbgvd";
import * as _dsbtrd from "./functions/dsbtrd";
import * as _dspcon from "./functions/dspcon";
import * as _dspev from "./functions/dspev";
import * as _dspevd from "./functions/dspevd";
import * as _dspgst from "./functions/dspgst";
import * as _dspgv from "./functions/dspgv";
import * as _dspgvd from "./functions/dspgvd";
import * as _dsprfs from "./functions/dsprfs";
import * as _dspsv from "./functions/dspsv";
import * as _dspsvx from "./functions/dspsvx";
import * as _dsptrd from "./functions/dsptrd";
import * as _dsptrf from "./functions/dsptrf";
import * as _dsptri from "./functions/dsptri";
import * as _dsptrs from "./functions/dsptrs";
import * as _dstebz from "./functions/dstebz";
import * as _dstedc from "./functions/dstedc";
import * as _dstein from "./functions/dstein";
import * as _dsteqr from "./functions/dsteqr";
import * as _dsterf from "./functions/dsterf";
import * as _dstev from "./functions/dstev";
import * as _dsycon from "./functions/dsycon";
import * as _dsyconv from "./functions/dsyconv";
import * as _dsyconvf from "./functions/dsyconvf";
import * as _dsyconvf_rook from "./functions/dsyconvf_rook";
import * as _dsycon_3 from "./functions/dsycon_3";
import * as _dsycon_rook from "./functions/dsycon_rook";
import * as _dsyequb from "./functions/dsyequb";
import * as _dsyev from "./functions/dsyev";
import * as _dsygs2 from "./functions/dsygs2";
import * as _dsygst from "./functions/dsygst";
import * as _dsygv from "./functions/dsygv";
import * as _dsygvd from "./functions/dsygvd";
import * as _dsygv_2stage from "./functions/dsygv_2stage";
import * as _dsyrfs from "./functions/dsyrfs";
import * as _dsysv from "./functions/dsysv";
import * as _dsysvx from "./functions/dsysvx";
import * as _dsysv_aa from "./functions/dsysv_aa";
import * as _dsysv_aa_2stage from "./functions/dsysv_aa_2stage";
import * as _dsysv_rk from "./functions/dsysv_rk";
import * as _dsysv_rook from "./functions/dsysv_rook";
import * as _dsyswapr from "./functions/dsyswapr";
import * as _dsytd2 from "./functions/dsytd2";
import * as _dsytf2 from "./functions/dsytf2";
import * as _dsytf2_rk from "./functions/dsytf2_rk";
import * as _dsytf2_rook from "./functions/dsytf2_rook";
import * as _dsytrd from "./functions/dsytrd";
import * as _dsytrd_sy2sb from "./functions/dsytrd_sy2sb";
import * as _dsytrf from "./functions/dsytrf";
import * as _dsytrf_aa from "./functions/dsytrf_aa";
import * as _dsytrf_aa_2stage from "./functions/dsytrf_aa_2stage";
import * as _dsytrf_rk from "./functions/dsytrf_rk";
import * as _dsytrf_rook from "./functions/dsytrf_rook";
import * as _dsytri from "./functions/dsytri";
import * as _dsytri2x from "./functions/dsytri2x";
import * as _dsytri_3x from "./functions/dsytri_3x";
import * as _dsytri_rook from "./functions/dsytri_rook";
import * as _dsytrs from "./functions/dsytrs";
import * as _dsytrs2 from "./functions/dsytrs2";
import * as _dsytrs_3 from "./functions/dsytrs_3";
import * as _dsytrs_aa from "./functions/dsytrs_aa";
import * as _dsytrs_aa_2stage from "./functions/dsytrs_aa_2stage";
import * as _dsytrs_rook from "./functions/dsytrs_rook";
import * as _dtbcon from "./functions/dtbcon";
import * as _dtbrfs from "./functions/dtbrfs";
import * as _dtbtrs from "./functions/dtbtrs";
import * as _dtfttp from "./functions/dtfttp";
import * as _dtfttr from "./functions/dtfttr";
import * as _dtgsja from "./functions/dtgsja";
import * as _dtgsy2 from "./functions/dtgsy2";
import * as _dtgsyl from "./functions/dtgsyl";
import * as _dtpcon from "./functions/dtpcon";
import * as _dtplqt from "./functions/dtplqt";
import * as _dtplqt2 from "./functions/dtplqt2";
import * as _dtpqrt from "./functions/dtpqrt";
import * as _dtpqrt2 from "./functions/dtpqrt2";
import * as _dtprfs from "./functions/dtprfs";
import * as _dtptri from "./functions/dtptri";
import * as _dtptrs from "./functions/dtptrs";
import * as _dtpttf from "./functions/dtpttf";
import * as _dtpttr from "./functions/dtpttr";
import * as _dtrcon from "./functions/dtrcon";
import * as _dtrexc from "./functions/dtrexc";
import * as _dtrrfs from "./functions/dtrrfs";
import * as _dtrsyl from "./functions/dtrsyl";
import * as _dtrti2 from "./functions/dtrti2";
import * as _dtrtri from "./functions/dtrtri";
import * as _dtrtrs from "./functions/dtrtrs";
import * as _dtrttp from "./functions/dtrttp";
import * as _dtzrzf from "./functions/dtzrzf";
export import dbbcsd = _dbbcsd.dbbcsd;
export import dbdsqr = _dbdsqr.dbdsqr;
export import ddisna = _ddisna.ddisna;
export import dgbbrd = _dgbbrd.dgbbrd;
export import dgbcon = _dgbcon.dgbcon;
export import dgbequ = _dgbequ.dgbequ;
export import dgbequb = _dgbequb.dgbequb;
export import dgbrfs = _dgbrfs.dgbrfs;
export import dgbsv = _dgbsv.dgbsv;
export import dgbsvx = _dgbsvx.dgbsvx;
export import dgbtf2 = _dgbtf2.dgbtf2;
export import dgbtrf = _dgbtrf.dgbtrf;
export import dgbtrs = _dgbtrs.dgbtrs;
export import dgebak = _dgebak.dgebak;
export import dgebal = _dgebal.dgebal;
export import dgebd2 = _dgebd2.dgebd2;
export import dgebrd = _dgebrd.dgebrd;
export import dgecon = _dgecon.dgecon;
export import dgeequ = _dgeequ.dgeequ;
export import dgeequb = _dgeequb.dgeequb;
export import dgeev = _dgeev.dgeev;
export import dgeevx = _dgeevx.dgeevx;
export import dgehd2 = _dgehd2.dgehd2;
export import dgehrd = _dgehrd.dgehrd;
export import dgejsv = _dgejsv.dgejsv;
export import dgelq = _dgelq.dgelq;
export import dgelq2 = _dgelq2.dgelq2;
export import dgelqf = _dgelqf.dgelqf;
export import dgelqt = _dgelqt.dgelqt;
export import dgels = _dgels.dgels;
export import dgelss = _dgelss.dgelss;
export import dgelsy = _dgelsy.dgelsy;
export import dgemqr = _dgemqr.dgemqr;
export import dgeql2 = _dgeql2.dgeql2;
export import dgeqlf = _dgeqlf.dgeqlf;
export import dgeqp3 = _dgeqp3.dgeqp3;
export import dgeqr = _dgeqr.dgeqr;
export import dgeqr2 = _dgeqr2.dgeqr2;
export import dgeqr2p = _dgeqr2p.dgeqr2p;
export import dgeqrf = _dgeqrf.dgeqrf;
export import dgeqrfp = _dgeqrfp.dgeqrfp;
export import dgeqrt = _dgeqrt.dgeqrt;
export import dgeqrt2 = _dgeqrt2.dgeqrt2;
export import dgerfs = _dgerfs.dgerfs;
export import dgerq2 = _dgerq2.dgerq2;
export import dgerqf = _dgerqf.dgerqf;
export import dgesc2 = _dgesc2.dgesc2;
export import dgesv = _dgesv.dgesv;
export import dgesvj = _dgesvj.dgesvj;
export import dgesvx = _dgesvx.dgesvx;
export import dgetc2 = _dgetc2.dgetc2;
export import dgetf2 = _dgetf2.dgetf2;
export import dgetrf = _dgetrf.dgetrf;
export import dgetri = _dgetri.dgetri;
export import dgetrs = _dgetrs.dgetrs;
export import dgetsls = _dgetsls.dgetsls;
export import dggbak = _dggbak.dggbak;
export import dggev = _dggev.dggev;
export import dggev3 = _dggev3.dggev3;
export import dggglm = _dggglm.dggglm;
export import dgghrd = _dgghrd.dgghrd;
export import dgglse = _dgglse.dgglse;
export import dggqrf = _dggqrf.dggqrf;
export import dggrqf = _dggrqf.dggrqf;
export import dggsvd3 = _dggsvd3.dggsvd3;
export import dggsvp3 = _dggsvp3.dggsvp3;
export import dgsvj0 = _dgsvj0.dgsvj0;
export import dgsvj1 = _dgsvj1.dgsvj1;
export import dgtcon = _dgtcon.dgtcon;
export import dgtrfs = _dgtrfs.dgtrfs;
export import dgtsv = _dgtsv.dgtsv;
export import dgtsvx = _dgtsvx.dgtsvx;
export import dgttrf = _dgttrf.dgttrf;
export import dgttrs = _dgttrs.dgttrs;
export import dgtts2 = _dgtts2.dgtts2;
export import dhgeqz = _dhgeqz.dhgeqz;
export import dhseqr = _dhseqr.dhseqr;
export import dlabad = _dlabad.dlabad;
export import dlabrd = _dlabrd.dlabrd;
export import dlacn2 = _dlacn2.dlacn2;
export import dlacon = _dlacon.dlacon;
export import dlacpy = _dlacpy.dlacpy;
export import dladiv = _dladiv.dladiv;
export import dlae2 = _dlae2.dlae2;
export import dlaebz = _dlaebz.dlaebz;
export import dlaed1 = _dlaed1.dlaed1;
export import dlaed2 = _dlaed2.dlaed2;
export import dlaed4 = _dlaed4.dlaed4;
export import dlaed5 = _dlaed5.dlaed5;
export import dlaed8 = _dlaed8.dlaed8;
export import dlaed9 = _dlaed9.dlaed9;
export import dlaev2 = _dlaev2.dlaev2;
export import dlag2 = _dlag2.dlag2;
export import dlag2s = _dlag2s.dlag2s;
export import dlagtf = _dlagtf.dlagtf;
export import dlagtm = _dlagtm.dlagtm;
export import dlagts = _dlagts.dlagts;
export import dlagv2 = _dlagv2.dlagv2;
export import dlahr2 = _dlahr2.dlahr2;
export import dlaic1 = _dlaic1.dlaic1;
export import dlamrg = _dlamrg.dlamrg;
export import dlanv2 = _dlanv2.dlanv2;
export import dlaqgb = _dlaqgb.dlaqgb;
export import dlaqge = _dlaqge.dlaqge;
export import dlaqp2 = _dlaqp2.dlaqp2;
export import dlaqr1 = _dlaqr1.dlaqr1;
export import dlaqsb = _dlaqsb.dlaqsb;
export import dlaqsp = _dlaqsp.dlaqsp;
export import dlaqsy = _dlaqsy.dlaqsy;
export import dlarnv = _dlarnv.dlarnv;
export import dlarra = _dlarra.dlarra;
export import dlarrb = _dlarrb.dlarrb;
export import dlarrc = _dlarrc.dlarrc;
export import dlarrd = _dlarrd.dlarrd;
export import dlarre = _dlarre.dlarre;
export import dlarrj = _dlarrj.dlarrj;
export import dlarrk = _dlarrk.dlarrk;
export import dlarrr = _dlarrr.dlarrr;
export import dlarrv = _dlarrv.dlarrv;
export import dlarscl2 = _dlarscl2.dlarscl2;
export import dlartg = _dlartg.dlartg;
export import dlartgp = _dlartgp.dlartgp;
export import dlartgs = _dlartgs.dlartgs;
export import dlaruv = _dlaruv.dlaruv;
export import dlas2 = _dlas2.dlas2;
export import dlascl = _dlascl.dlascl;
export import dlasd4 = _dlasd4.dlasd4;
export import dlasd5 = _dlasd5.dlasd5;
export import dlasdt = _dlasdt.dlasdt;
export import dlaset = _dlaset.dlaset;
export import dlasq1 = _dlasq1.dlasq1;
export import dlasq2 = _dlasq2.dlasq2;
export import dlasq4 = _dlasq4.dlasq4;
export import dlasrt = _dlasrt.dlasrt;
export import dlassq = _dlassq.dlassq;
export import dlasv2 = _dlasv2.dlasv2;
export import dlasyf = _dlasyf.dlasyf;
export import dlasyf_aa = _dlasyf_aa.dlasyf_aa;
export import dlasyf_rk = _dlasyf_rk.dlasyf_rk;
export import dlasyf_rook = _dlasyf_rook.dlasyf_rook;
export import dlat2s = _dlat2s.dlat2s;
export import dlatbs = _dlatbs.dlatbs;
export import dlatdf = _dlatdf.dlatdf;
export import dlatps = _dlatps.dlatps;
export import dlatrd = _dlatrd.dlatrd;
export import dlatrs = _dlatrs.dlatrs;
export import dlatrz = _dlatrz.dlatrz;
export import dlauu2 = _dlauu2.dlauu2;
export import dlauum = _dlauum.dlauum;
export import dla_lin_berr = _dla_lin_berr.dla_lin_berr;
export import dla_wwaddw = _dla_wwaddw.dla_wwaddw;
export import dopgtr = _dopgtr.dopgtr;
export import dorbdb = _dorbdb.dorbdb;
export import dorbdb1 = _dorbdb1.dorbdb1;
export import dorbdb2 = _dorbdb2.dorbdb2;
export import dorbdb3 = _dorbdb3.dorbdb3;
export import dorbdb4 = _dorbdb4.dorbdb4;
export import dorbdb5 = _dorbdb5.dorbdb5;
export import dorbdb6 = _dorbdb6.dorbdb6;
export import dorg2l = _dorg2l.dorg2l;
export import dorg2r = _dorg2r.dorg2r;
export import dorghr = _dorghr.dorghr;
export import dorgl2 = _dorgl2.dorgl2;
export import dorglq = _dorglq.dorglq;
export import dorgql = _dorgql.dorgql;
export import dorgqr = _dorgqr.dorgqr;
export import dorgr2 = _dorgr2.dorgr2;
export import dorgrq = _dorgrq.dorgrq;
export import dorgtr = _dorgtr.dorgtr;
export import dormql = _dormql.dormql;
export import dormqr = _dormqr.dormqr;
export import dpbcon = _dpbcon.dpbcon;
export import dpbequ = _dpbequ.dpbequ;
export import dpbrfs = _dpbrfs.dpbrfs;
export import dpbstf = _dpbstf.dpbstf;
export import dpbsv = _dpbsv.dpbsv;
export import dpbsvx = _dpbsvx.dpbsvx;
export import dpbtf2 = _dpbtf2.dpbtf2;
export import dpbtrf = _dpbtrf.dpbtrf;
export import dpbtrs = _dpbtrs.dpbtrs;
export import dpftrf = _dpftrf.dpftrf;
export import dpftri = _dpftri.dpftri;
export import dpftrs = _dpftrs.dpftrs;
export import dpocon = _dpocon.dpocon;
export import dpoequ = _dpoequ.dpoequ;
export import dpoequb = _dpoequb.dpoequb;
export import dporfs = _dporfs.dporfs;
export import dposv = _dposv.dposv;
export import dposvx = _dposvx.dposvx;
export import dpotf2 = _dpotf2.dpotf2;
export import dpotrf = _dpotrf.dpotrf;
export import dpotri = _dpotri.dpotri;
export import dpotrs = _dpotrs.dpotrs;
export import dppcon = _dppcon.dppcon;
export import dppequ = _dppequ.dppequ;
export import dpprfs = _dpprfs.dpprfs;
export import dppsv = _dppsv.dppsv;
export import dppsvx = _dppsvx.dppsvx;
export import dpptrf = _dpptrf.dpptrf;
export import dpptri = _dpptri.dpptri;
export import dpptrs = _dpptrs.dpptrs;
export import dpstf2 = _dpstf2.dpstf2;
export import dpstrf = _dpstrf.dpstrf;
export import dptcon = _dptcon.dptcon;
export import dpteqr = _dpteqr.dpteqr;
export import dptrfs = _dptrfs.dptrfs;
export import dptsv = _dptsv.dptsv;
export import dptsvx = _dptsvx.dptsvx;
export import dpttrf = _dpttrf.dpttrf;
export import dpttrs = _dpttrs.dpttrs;
export import dptts2 = _dptts2.dptts2;
export import dsbev = _dsbev.dsbev;
export import dsbgst = _dsbgst.dsbgst;
export import dsbgv = _dsbgv.dsbgv;
export import dsbgvd = _dsbgvd.dsbgvd;
export import dsbtrd = _dsbtrd.dsbtrd;
export import dspcon = _dspcon.dspcon;
export import dspev = _dspev.dspev;
export import dspevd = _dspevd.dspevd;
export import dspgst = _dspgst.dspgst;
export import dspgv = _dspgv.dspgv;
export import dspgvd = _dspgvd.dspgvd;
export import dsprfs = _dsprfs.dsprfs;
export import dspsv = _dspsv.dspsv;
export import dspsvx = _dspsvx.dspsvx;
export import dsptrd = _dsptrd.dsptrd;
export import dsptrf = _dsptrf.dsptrf;
export import dsptri = _dsptri.dsptri;
export import dsptrs = _dsptrs.dsptrs;
export import dstebz = _dstebz.dstebz;
export import dstedc = _dstedc.dstedc;
export import dstein = _dstein.dstein;
export import dsteqr = _dsteqr.dsteqr;
export import dsterf = _dsterf.dsterf;
export import dstev = _dstev.dstev;
export import dsycon = _dsycon.dsycon;
export import dsyconv = _dsyconv.dsyconv;
export import dsyconvf = _dsyconvf.dsyconvf;
export import dsyconvf_rook = _dsyconvf_rook.dsyconvf_rook;
export import dsycon_3 = _dsycon_3.dsycon_3;
export import dsycon_rook = _dsycon_rook.dsycon_rook;
export import dsyequb = _dsyequb.dsyequb;
export import dsyev = _dsyev.dsyev;
export import dsygs2 = _dsygs2.dsygs2;
export import dsygst = _dsygst.dsygst;
export import dsygv = _dsygv.dsygv;
export import dsygvd = _dsygvd.dsygvd;
export import dsygv_2stage = _dsygv_2stage.dsygv_2stage;
export import dsyrfs = _dsyrfs.dsyrfs;
export import dsysv = _dsysv.dsysv;
export import dsysvx = _dsysvx.dsysvx;
export import dsysv_aa = _dsysv_aa.dsysv_aa;
export import dsysv_aa_2stage = _dsysv_aa_2stage.dsysv_aa_2stage;
export import dsysv_rk = _dsysv_rk.dsysv_rk;
export import dsysv_rook = _dsysv_rook.dsysv_rook;
export import dsyswapr = _dsyswapr.dsyswapr;
export import dsytd2 = _dsytd2.dsytd2;
export import dsytf2 = _dsytf2.dsytf2;
export import dsytf2_rk = _dsytf2_rk.dsytf2_rk;
export import dsytf2_rook = _dsytf2_rook.dsytf2_rook;
export import dsytrd = _dsytrd.dsytrd;
export import dsytrd_sy2sb = _dsytrd_sy2sb.dsytrd_sy2sb;
export import dsytrf = _dsytrf.dsytrf;
export import dsytrf_aa = _dsytrf_aa.dsytrf_aa;
export import dsytrf_aa_2stage = _dsytrf_aa_2stage.dsytrf_aa_2stage;
export import dsytrf_rk = _dsytrf_rk.dsytrf_rk;
export import dsytrf_rook = _dsytrf_rook.dsytrf_rook;
export import dsytri = _dsytri.dsytri;
export import dsytri2x = _dsytri2x.dsytri2x;
export import dsytri_3x = _dsytri_3x.dsytri_3x;
export import dsytri_rook = _dsytri_rook.dsytri_rook;
export import dsytrs = _dsytrs.dsytrs;
export import dsytrs2 = _dsytrs2.dsytrs2;
export import dsytrs_3 = _dsytrs_3.dsytrs_3;
export import dsytrs_aa = _dsytrs_aa.dsytrs_aa;
export import dsytrs_aa_2stage = _dsytrs_aa_2stage.dsytrs_aa_2stage;
export import dsytrs_rook = _dsytrs_rook.dsytrs_rook;
export import dtbcon = _dtbcon.dtbcon;
export import dtbrfs = _dtbrfs.dtbrfs;
export import dtbtrs = _dtbtrs.dtbtrs;
export import dtfttp = _dtfttp.dtfttp;
export import dtfttr = _dtfttr.dtfttr;
export import dtgsja = _dtgsja.dtgsja;
export import dtgsy2 = _dtgsy2.dtgsy2;
export import dtgsyl = _dtgsyl.dtgsyl;
export import dtpcon = _dtpcon.dtpcon;
export import dtplqt = _dtplqt.dtplqt;
export import dtplqt2 = _dtplqt2.dtplqt2;
export import dtpqrt = _dtpqrt.dtpqrt;
export import dtpqrt2 = _dtpqrt2.dtpqrt2;
export import dtprfs = _dtprfs.dtprfs;
export import dtptri = _dtptri.dtptri;
export import dtptrs = _dtptrs.dtptrs;
export import dtpttf = _dtpttf.dtpttf;
export import dtpttr = _dtpttr.dtpttr;
export import dtrcon = _dtrcon.dtrcon;
export import dtrexc = _dtrexc.dtrexc;
export import dtrrfs = _dtrrfs.dtrrfs;
export import dtrsyl = _dtrsyl.dtrsyl;
export import dtrti2 = _dtrti2.dtrti2;
export import dtrtri = _dtrtri.dtrtri;
export import dtrtrs = _dtrtrs.dtrtrs;
export import dtrttp = _dtrttp.dtrttp;
export import dtzrzf = _dtzrzf.dtzrzf;
